// Data extracted/synthesized from the BC AI healthcare repo content.
// Roles, organizations, topics, guidelines, updates.

const ROLES = [
  { id: "physician",   label: "Physician" },
  { id: "nurse",       label: "Nurse" },
  { id: "allied",      label: "Allied health" },
  { id: "admin",       label: "Administrator" },
  { id: "researcher",  label: "Researcher" },
  { id: "student",     label: "Student / trainee" },
];

const ORGS = [
  { id: "cpsbc",       short: "CPSBC",  name: "College of Physicians & Surgeons of BC", kind: "professional-college", tinted: true },
  { id: "ai4h",        short: "AI4H",   name: "Pan-Canadian AI for Health (Health Canada)", kind: "federal" },
  { id: "oipc",        short: "OIPC",   name: "Office of the Information & Privacy Commissioner BC", kind: "government" },
  { id: "doctorsbc",   short: "DoBC",   name: "Doctors of BC", kind: "physician-society" },
  { id: "phsa",        short: "PHSA",   name: "Provincial Health Services Authority", kind: "provincial-authority" },
  { id: "vch",         short: "VCH",    name: "Vancouver Coastal Health / VCHRI", kind: "regional-health-authority" },
  { id: "bccnm",       short: "BCCNM",  name: "BC College of Nurses & Midwives", kind: "professional-college" },
  { id: "fraser",      short: "FH",     name: "Fraser Health", kind: "regional-health-authority" },
  { id: "interior",    short: "IH",     name: "Interior Health", kind: "regional-health-authority" },
  { id: "island",      short: "VIH",    name: "Island Health", kind: "regional-health-authority" },
  { id: "northern",    short: "NH",     name: "Northern Health", kind: "regional-health-authority" },
  { id: "moh",         short: "MoH",    name: "BC Ministry of Health", kind: "government" },
  { id: "cma",         short: "CMA",    name: "Canadian Medical Association", kind: "physician-society" },
  { id: "opc",         short: "OPC",    name: "Office of the Privacy Commissioner of Canada", kind: "federal" },
];

const TOPICS = [
  { id: "privacy",        label: "Privacy",            color: "var(--t-privacy)" },
  { id: "consent",        label: "Consent",            color: "var(--t-consent)" },
  { id: "safety",         label: "Safety & oversight", color: "var(--t-safety)" },
  { id: "bias",           label: "Bias & EDI",         color: "var(--t-bias)" },
  { id: "transparency",   label: "Transparency",       color: "var(--t-transparency)" },
  { id: "accountability", label: "Accountability",     color: "var(--t-accountability)" },
  { id: "clinical",       label: "Clinical decision support", color: "var(--t-clinical)" },
  { id: "documentation",  label: "AI scribes & docs",  color: "var(--t-documentation)" },
  { id: "procurement",    label: "Procurement",        color: "var(--t-procurement)" },
  { id: "education",      label: "Education & literacy", color: "var(--t-education)" },
];

const TYPES = [
  { id: "guideline",  label: "Guideline" },
  { id: "policy",     label: "Policy" },
  { id: "principles", label: "Guiding principles" },
  { id: "position",   label: "Position statement" },
  { id: "toolkit",    label: "Toolkit" },
  { id: "checklist",  label: "Checklist" },
  { id: "faq",        label: "FAQ" },
];

const GUIDELINES = [
  {
    id: "cpsbc-ai-ethics",
    title: "Ethical Principles for Artificial Intelligence in Medicine",
    org: "cpsbc",
    type: "guideline",
    scope: "bc-wide",
    region: "British Columbia",
    updated: "2026-04-01",
    verified: "2026-04-22",
    audiences: ["physician", "admin", "student"],
    topics: ["consent","privacy","bias","safety","accountability","transparency","documentation"],
    summary: "Interim College guidance covering privacy, consent, accuracy, transparency, bias and monitoring expectations when physicians integrate AI — including documentation tools and scribes.",
    whoFor: [
      "Practising BC physicians and surgeons integrating AI into care",
      "Group practices procuring AI scribes or clinical decision support",
      "Trainees observing AI-assisted documentation",
    ],
    keyPoints: [
      { h: "Meaningful consent", b: "Patients (or substitute decision-makers) understand when audio, dictation, or AI-assisted documentation is in use, and may refuse." },
      { h: "Know the data flow", b: "Be able to describe where information goes — on-device, hospital-managed, or vendor cloud — and the retention/deletion expectations." },
      { h: "Review before signing", b: "AI-generated notes are reviewed before signing or sharing; errors corrected promptly." },
      { h: "Plan for sensitive content", b: "Have a plan for trauma, stigma, or other sensitive content where recording or cloud processing is inappropriate." },
      { h: "Equity in language", b: "Consider whether the tool handles names, pronouns, community terms, and culturally specific content respectfully." },
      { h: "Local oversight", b: "There is a named site point person or policy for incidents — mis-transcription, privacy concerns, or vendor changes." },
    ],
    related: ["ai4h-principles", "oipc-pipa-ai", "bccnm-ai-practice"],
    sourceUrl: "https://www.cpsbc.ca/files/pdf/CPSBC-PG-Artificial-Intelligence.pdf",
    pages: 14,
  },
  {
    id: "ai4h-principles",
    title: "Pan-Canadian AI for Health — Guiding Principles",
    org: "ai4h",
    type: "principles",
    scope: "pan-canadian",
    region: "Canada",
    updated: "2025-01-15",
    verified: "2026-03-08",
    audiences: ["admin","researcher","physician"],
    topics: ["bias","privacy","safety","transparency","accountability"],
    summary: "Six principles — person-centricity, EDI, privacy & security, safety & assurance, transparency, accountability — endorsed by F/P/T health ministers to anchor AI adoption in Canadian care.",
    whoFor: [
      "F/P/T health-system planners shaping AI procurement",
      "Health authorities aligning local policy with national language",
      "Researchers framing impact statements for funded AI work",
    ],
    keyPoints: [
      { h: "Person-centricity", b: "The well-being of people in Canada, including equity-seeking groups, shapes how AI is adopted, governed, and evaluated." },
      { h: "Equity, diversity & inclusion", b: "AI should narrow gaps, not widen them. Check training data, validation cohorts, and downstream access effects." },
      { h: "Privacy & security", b: "Health information used with AI must be protected through consent, minimization, safeguards, and clear accountability." },
      { h: "Safety & assurance", b: "AI systems should be sufficiently safe for their intended use, with monitoring, incident learning, and human oversight." },
      { h: "Transparency & explainability", b: "People affected by AI-assisted decisions receive understandable information about how AI is used and its limits." },
      { h: "Accountability & oversight", b: "Roles across vendors, organizations, and clinicians are clear, with governance that adapts as technology changes." },
    ],
    related: ["cpsbc-ai-ethics","cma-ai-position","health-canada-saMd"],
    sourceUrl: "https://www.canada.ca/en/health-canada/corporate/transparency/health-agreements/pan-canadian-ai-guiding-principles.html",
  },
  {
    id: "oipc-pipa-ai",
    title: "PIPA AI Scribes Checklist & Commissioner Guidance",
    org: "oipc",
    type: "checklist",
    scope: "bc-wide",
    region: "British Columbia",
    updated: "2026-01-28",
    verified: "2026-02-14",
    audiences: ["physician","admin"],
    topics: ["privacy","consent","procurement","documentation"],
    summary: "OIPC checklist clarifying how BC private- and public-sector privacy instruments attach when SaaS transcription or analytics clouds touch health data.",
    whoFor: [
      "Privacy officers reviewing scribe vendors",
      "Clinics procuring transcription SaaS",
      "Researchers using cloud-hosted analytics on PHI",
    ],
    keyPoints: [
      { h: "Vendor data flow", b: "Map subprocessors and storage jurisdictions before sign-off; PIPA attaches even when vendor terms are silent." },
      { h: "Meaningful consent", b: "Document the consent moment and the alternative offered if a patient declines." },
      { h: "Breach response", b: "Pre-arrange the breach pathway with the vendor — including timing and notification responsibility." },
      { h: "Retention", b: "Confirm retention/deletion and the audit log for access requests." },
    ],
    related: ["cpsbc-ai-ethics","opc-pipeda-ai"],
    sourceUrl: "https://www.oipc.bc.ca/",
  },
  {
    id: "doctorsbc-ai-policy",
    title: "Navigating AI Policy in Health Care",
    org: "doctorsbc",
    type: "position",
    scope: "bc-wide",
    region: "British Columbia",
    updated: "2025-05-12",
    verified: "2026-01-30",
    audiences: ["physician","admin"],
    topics: ["accountability","bias","education","procurement"],
    summary: "Doctors of BC's policy currents on equity, professionalism, and the rollout of AI tools — sitting alongside CPSBC interim guidance and college expectations.",
    whoFor: [
      "Practising members assessing new AI tooling",
      "Section heads navigating MSP documentation rules",
      "Members weighing equity & anti-racism commitments",
    ],
    keyPoints: [
      { h: "Professionalism still leads", b: "AI tools don't shift the locus of professional accountability away from the physician of record." },
      { h: "Equity-aware adoption", b: "Mind the equity-seeking groups in your panel when training data, validation cohorts, or workflows shift." },
      { h: "Documentation rules unchanged", b: "MSP documentation expectations apply whether a note was authored, dictated, or AI-drafted." },
    ],
    related: ["cpsbc-ai-ethics","cma-ai-position"],
    sourceUrl: "https://www.doctorsbc.ca/",
  },
  {
    id: "vch-ai-hub",
    title: "VCH / VCHRI AI Hub — Local Governance Framework",
    org: "vch",
    type: "policy",
    scope: "vch",
    region: "Vancouver Coastal",
    updated: "2026-03-04",
    verified: "2026-03-12",
    audiences: ["researcher","admin","physician"],
    topics: ["procurement","safety","accountability","clinical"],
    summary: "VCH's AI Hub leadership and intake framework for clinical & research AI projects — privacy, IT, REB and clinical sponsorship requirements.",
    whoFor: [
      "VCH clinicians piloting AI tools",
      "VCHRI investigators with AI components",
      "Department heads sponsoring an AI deployment",
    ],
    keyPoints: [
      { h: "Single intake", b: "All clinical/research AI projects flow through Hub intake before procurement or PHI exposure." },
      { h: "Sponsor required", b: "Each pilot needs a clinical sponsor accountable for incident response and decommissioning." },
      { h: "Outcomes review", b: "Quarterly outcomes review with the Hub steering committee." },
    ],
    related: ["phsa-ai-research","cpsbc-ai-ethics"],
    sourceUrl: "https://www.vchri.ca/services/additional-support/vch-vchri-ai-hub",
  },
  {
    id: "bccnm-ai-practice",
    title: "AI in Nursing & Midwifery Practice",
    org: "bccnm",
    type: "guideline",
    scope: "bc-wide",
    region: "British Columbia",
    updated: "2024-11-09",
    verified: "2025-12-15",
    audiences: ["nurse","allied","admin","student"],
    topics: ["consent","accountability","education","safety"],
    summary: "BCCNM's practice guidance on AI tools in nursing and midwifery — accountability for patient safety, consent, and continuing competence.",
    whoFor: [
      "RNs, RPNs, LPNs, and midwives using AI tools",
      "Educators developing AI literacy modules",
    ],
    keyPoints: [
      { h: "Scope of practice unchanged", b: "AI does not extend or modify your scope; competence and accountability remain with the registrant." },
      { h: "Continuing competence", b: "Maintain AI literacy as part of continuing competence, including a basic understanding of model limits." },
      { h: "Consent & dignity", b: "Patient dignity, consent, and cultural safety considerations apply equally to AI-assisted workflows." },
    ],
    related: ["cpsbc-ai-ethics","cma-ai-position"],
    sourceUrl: "https://www.bccnm.ca/",
  },
  {
    id: "phsa-ai-research",
    title: "PHSA AI Research Toolkit",
    org: "phsa",
    type: "toolkit",
    scope: "phsa",
    region: "Provincial",
    updated: "2025-09-22",
    verified: "2026-02-02",
    audiences: ["researcher","admin","student"],
    topics: ["bias","privacy","education","accountability","clinical"],
    summary: "PHSA's toolkit for researchers using generative AI: working-group guidance, mitigation patterns for plagiarism/PHI/bias, and a learning hub.",
    whoFor: [
      "PHSA-affiliated investigators",
      "Trainees writing protocols that use generative AI",
      "REB members reviewing AI-related submissions",
    ],
    keyPoints: [
      { h: "PHI never leaves the perimeter", b: "No PHI to public-tier generative tools — period. Use the institutional pipeline." },
      { h: "Plagiarism & provenance", b: "Disclose AI assistance in writing, code, and analysis; archive prompt + output where reproducibility matters." },
      { h: "Tri-agency alignment", b: "Align with tri-agency guidance on AI use in funded research." },
    ],
    related: ["vch-ai-hub","ai4h-principles"],
    sourceUrl: "https://www.phsa.ca/researcher/resources/artificial-intelligence",
  },
  {
    id: "cma-ai-position",
    title: "CMA Position on Artificial Intelligence in Medicine",
    org: "cma",
    type: "position",
    scope: "pan-canadian",
    region: "Canada",
    updated: "2024-10-04",
    verified: "2025-11-19",
    audiences: ["physician","admin"],
    topics: ["accountability","bias","transparency","education"],
    summary: "CMA's national position framing physician accountability, education, and equitable AI deployment across Canadian health systems.",
    whoFor: [
      "CMA members forming local policy",
      "Health-system planners citing national positions",
    ],
    keyPoints: [
      { h: "Education before deployment", b: "AI literacy is foundational — build it into UME, residency, and CPD." },
      { h: "Validation in Canadian populations", b: "Tools deployed in Canada should be validated in Canadian cohorts where it matters." },
      { h: "Algorithmic transparency", b: "Patients and clinicians have a right to understand how AI shapes a recommendation." },
    ],
    related: ["ai4h-principles","doctorsbc-ai-policy"],
    sourceUrl: "https://www.cma.ca/ai",
  },
  {
    id: "opc-pipeda-ai",
    title: "PIPEDA & Federal Guidance on Health AI Processors",
    org: "opc",
    type: "guideline",
    scope: "federal",
    region: "Canada",
    updated: "2025-08-19",
    verified: "2026-01-04",
    audiences: ["admin","researcher"],
    topics: ["privacy","procurement","accountability","transparency"],
    summary: "OPC interpretations relevant to commercial health-SaaS pipelines — lawful basis, accountability, and algorithmic transparency hooks.",
    whoFor: ["Privacy officers", "Procurement leads"],
    keyPoints: [
      { h: "Lawful basis", b: "Establish lawful basis early — purposes documented before contracting." },
      { h: "Accountability anchor", b: "Name the accountable individual for the AI deployment, with audit rights to subprocessors." },
    ],
    related: ["oipc-pipa-ai","ai4h-principles"],
    sourceUrl: "https://www.priv.gc.ca/en/privacy-topics/technology-artificial-intelligence/",
  },
];

const UPDATES = [
  { id: "u1", date: "2026-04-22", org: "cpsbc",     title: "AI in Medicine — Version 1.2 published", summary: "Adds explicit language on AI scribes and clarifies the consent moment.", topics: ["documentation","consent"], guidelineId: "cpsbc-ai-ethics" },
  { id: "u2", date: "2026-03-12", org: "vch",       title: "VCH/VCHRI AI Hub — new director appointed", summary: "Hub intake reopens; updated sponsor & outcomes-review process.", topics: ["procurement","accountability"], guidelineId: "vch-ai-hub" },
  { id: "u3", date: "2026-02-14", org: "oipc",      title: "PIPA AI Scribes Checklist refresh", summary: "OIPC adds a sub-processor mapping table and breach-window guidance.", topics: ["privacy","documentation"], guidelineId: "oipc-pipa-ai" },
  { id: "u4", date: "2026-02-02", org: "phsa",      title: "PHSA Research Toolkit minor update", summary: "Tri-agency alignment notes refreshed; prompt-archive guidance.", topics: ["education","accountability"], guidelineId: "phsa-ai-research" },
  { id: "u5", date: "2026-01-30", org: "doctorsbc", title: "Member bulletin — AI tooling and MSP rules", summary: "Reinforces that documentation rules apply equally to AI-drafted notes.", topics: ["documentation","accountability"], guidelineId: "doctorsbc-ai-policy" },
  { id: "u6", date: "2026-01-04", org: "opc",       title: "OPC commentary on health-SaaS subprocessors", summary: "Federal guidance on audit rights when health pipelines cross borders.", topics: ["privacy","procurement"], guidelineId: "opc-pipeda-ai" },
  { id: "u7", date: "2025-12-15", org: "bccnm",     title: "Continuing competence — AI literacy module", summary: "BCCNM adds an AI literacy module to continuing-competence resources.", topics: ["education"], guidelineId: "bccnm-ai-practice" },
  { id: "u8", date: "2025-11-19", org: "cma",       title: "CMA reaffirms validation expectations", summary: "Brief reaffirming Canadian-cohort validation and transparency.", topics: ["bias","transparency"], guidelineId: "cma-ai-position" },
  { id: "u9", date: "2025-09-22", org: "phsa",      title: "AI Research Toolkit — major release", summary: "Full toolkit re-released with mitigation patterns and a learning hub.", topics: ["education","bias"], guidelineId: "phsa-ai-research" },
];

const PRINCIPLES = [
  { id: "person",         num: "P01", title: "Person-centricity",          color: "var(--t-clinical)" },
  { id: "edi",            num: "P02", title: "Equity, diversity, inclusion", color: "var(--t-bias)" },
  { id: "privacy",        num: "P03", title: "Privacy & security",          color: "var(--t-privacy)" },
  { id: "safety",         num: "P04", title: "Safety & assurance",          color: "var(--t-safety)" },
  { id: "transparency",   num: "P05", title: "Transparency & explainability", color: "var(--t-transparency)" },
  { id: "accountability", num: "P06", title: "Accountability & oversight",  color: "var(--t-accountability)" },
];

window.HUB_DATA = { ROLES, ORGS, TOPICS, TYPES, GUIDELINES, UPDATES, PRINCIPLES };
