/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MythBustingRouteImport } from './routes/myth-busting'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as GlobalComparisonRouteImport } from './routes/global-comparison'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BcHealthAuthoritiesRouteImport } from './routes/bc-health-authorities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MythBustingRoute = MythBustingRouteImport.update({
  id: '/myth-busting',
  path: '/myth-busting',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalComparisonRoute = GlobalComparisonRouteImport.update({
  id: '/global-comparison',
  path: '/global-comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BcHealthAuthoritiesRoute = BcHealthAuthoritiesRouteImport.update({
  id: '/bc-health-authorities',
  path: '/bc-health-authorities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bc-health-authorities': typeof BcHealthAuthoritiesRoute
  '/case-studies': typeof CaseStudiesRoute
  '/checklists': typeof ChecklistsRoute
  '/ecosystem': typeof EcosystemRoute
  '/global-comparison': typeof GlobalComparisonRoute
  '/guidelines': typeof GuidelinesRoute
  '/myth-busting': typeof MythBustingRoute
  '/privacy': typeof PrivacyRoute
  '/updates': typeof UpdatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bc-health-authorities': typeof BcHealthAuthoritiesRoute
  '/case-studies': typeof CaseStudiesRoute
  '/checklists': typeof ChecklistsRoute
  '/ecosystem': typeof EcosystemRoute
  '/global-comparison': typeof GlobalComparisonRoute
  '/guidelines': typeof GuidelinesRoute
  '/myth-busting': typeof MythBustingRoute
  '/privacy': typeof PrivacyRoute
  '/updates': typeof UpdatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bc-health-authorities': typeof BcHealthAuthoritiesRoute
  '/case-studies': typeof CaseStudiesRoute
  '/checklists': typeof ChecklistsRoute
  '/ecosystem': typeof EcosystemRoute
  '/global-comparison': typeof GlobalComparisonRoute
  '/guidelines': typeof GuidelinesRoute
  '/myth-busting': typeof MythBustingRoute
  '/privacy': typeof PrivacyRoute
  '/updates': typeof UpdatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bc-health-authorities'
    | '/case-studies'
    | '/checklists'
    | '/ecosystem'
    | '/global-comparison'
    | '/guidelines'
    | '/myth-busting'
    | '/privacy'
    | '/updates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bc-health-authorities'
    | '/case-studies'
    | '/checklists'
    | '/ecosystem'
    | '/global-comparison'
    | '/guidelines'
    | '/myth-busting'
    | '/privacy'
    | '/updates'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bc-health-authorities'
    | '/case-studies'
    | '/checklists'
    | '/ecosystem'
    | '/global-comparison'
    | '/guidelines'
    | '/myth-busting'
    | '/privacy'
    | '/updates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BcHealthAuthoritiesRoute: typeof BcHealthAuthoritiesRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ChecklistsRoute: typeof ChecklistsRoute
  EcosystemRoute: typeof EcosystemRoute
  GlobalComparisonRoute: typeof GlobalComparisonRoute
  GuidelinesRoute: typeof GuidelinesRoute
  MythBustingRoute: typeof MythBustingRoute
  PrivacyRoute: typeof PrivacyRoute
  UpdatesRoute: typeof UpdatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myth-busting': {
      id: '/myth-busting'
      path: '/myth-busting'
      fullPath: '/myth-busting'
      preLoaderRoute: typeof MythBustingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-comparison': {
      id: '/global-comparison'
      path: '/global-comparison'
      fullPath: '/global-comparison'
      preLoaderRoute: typeof GlobalComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bc-health-authorities': {
      id: '/bc-health-authorities'
      path: '/bc-health-authorities'
      fullPath: '/bc-health-authorities'
      preLoaderRoute: typeof BcHealthAuthoritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BcHealthAuthoritiesRoute: BcHealthAuthoritiesRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ChecklistsRoute: ChecklistsRoute,
  EcosystemRoute: EcosystemRoute,
  GlobalComparisonRoute: GlobalComparisonRoute,
  GuidelinesRoute: GuidelinesRoute,
  MythBustingRoute: MythBustingRoute,
  PrivacyRoute: PrivacyRoute,
  UpdatesRoute: UpdatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
